flags:
  mersenne-random:
    use_sse2: true
extra-package-dbs: []
packages:
  - .
extra-deps:
  - mersenne-random-1.0.0.1
  - algebra-4.3
  - derive-storable-0.1.1.1
resolver: lts-9.18

build:
  haddock-arguments:
    haddock-args:
      - "--html-location='http://hackage.haskell.org/packages/archive/$pkg/latest/doc/html'"
  haddock-deps: false
